/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeitorRouteImport } from './routes/leitor'
import { Route as ConsultaAlunoIdRouteImport } from './routes/consulta.$alunoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeitorRoute = LeitorRouteImport.update({
  id: '/leitor',
  path: '/leitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaAlunoIdRoute = ConsultaAlunoIdRouteImport.update({
  id: '/consulta/$alunoId',
  path: '/consulta/$alunoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leitor': typeof LeitorRoute
  '/consulta/$alunoId': typeof ConsultaAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leitor': typeof LeitorRoute
  '/consulta/$alunoId': typeof ConsultaAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leitor': typeof LeitorRoute
  '/consulta/$alunoId': typeof ConsultaAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leitor' | '/consulta/$alunoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leitor' | '/consulta/$alunoId'
  id: '__root__' | '/' | '/leitor' | '/consulta/$alunoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeitorRoute: typeof LeitorRoute
  ConsultaAlunoIdRoute: typeof ConsultaAlunoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitor': {
      id: '/leitor'
      path: '/leitor'
      fullPath: '/leitor'
      preLoaderRoute: typeof LeitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/$alunoId': {
      id: '/consulta/$alunoId'
      path: '/consulta/$alunoId'
      fullPath: '/consulta/$alunoId'
      preLoaderRoute: typeof ConsultaAlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeitorRoute: LeitorRoute,
  ConsultaAlunoIdRoute: ConsultaAlunoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
